#!/bin/bash
# PIFGenerator by Juleast @ https://github.com/juleast
# Scripts to generate pif config fingerprints
# The generate() function segment is based on gen_pif_custom.sh by osm0sis @ xda-developers

# Remember original path
og_path=$(pwd)

megamind() {
  local message="$1"
  echo -e "———————————${message}?———————————"
  echo -e "⠀⣞⢽⢪⢣⢣⢣⢫⡺⡵⣝⡮⣗⢷⢽⢽⢽⣮⡷⡽⣜⣜⢮⢺⣜⢷⢽⢝⡽⣝"
  echo -e "⠸⡸⠜⠕⠕⠁⢁⢇⢏⢽⢺⣪⡳⡝⣎⣏⢯⢞⡿⣟⣷⣳⢯⡷⣽⢽⢯⣳⣫⠇"
  echo -e "⠀⠀⢀⢀⢄⢬⢪⡪⡎⣆⡈⠚⠜⠕⠇⠗⠝⢕⢯⢫⣞⣯⣿⣻⡽⣏⢗⣗⠏⠀"
  echo -e "⠀⠪⡪⡪⣪⢪⢺⢸⢢⢓⢆⢤⢀⠀⠀⠀⠀⠈⢊⢞⡾⣿⡯⣏⢮⠷⠁⠀⠀"
  echo -e "⠀⠀⠀⠈⠊⠆⡃⠕⢕⢇⢇⢇⢇⢇⢏⢎⢎⢆⢄⠀⢑⣽⣿⢝⠲⠉⠀⠀⠀⠀"
  echo -e "⠀⠀⠀⠀⠀⡿⠂⠠⠀⡇⢇⠕⢈⣀⠀⠁⠡⠣⡣⡫⣂⣿⠯⢪⠰⠂⠀⠀⠀⠀"
  echo -e "⠀⠀⠀⠀⡦⡙⡂⢀⢤⢣⠣⡈⣾⡃⠠⠄⠀⡄⢱⣌⣶⢏⢊⠂⠀⠀⠀⠀⠀⠀"
  echo -e "⠀⠀⠀⠀⢝⡲⣜⡮⡏⢎⢌⢂⠙⠢⠐⢀⢘⢵⣽⣿⡿⠁⠁⠀⠀⠀⠀⠀⠀⠀"
  echo -e "⠀⠀⠀⠀⠨⣺⡺⡕⡕⡱⡑⡆⡕⡅⡕⡜⡼⢽⡻⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
  echo -e "⠀⠀⠀⠀⣼⣳⣫⣾⣵⣗⡵⡱⡡⢣⢑⢕⢜⢕⡝⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
  echo -e "⠀⠀⠀⣴⣿⣾⣿⣿⣿⡿⡽⡑⢌⠪⡢⡣⣣⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
  echo -e "⠀⠀⠀⡟⡾⣿⢿⢿⢵⣽⣾⣼⣘⢸⢸⣞⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
  echo -e "⠀⠀⠀⠀⠁⠇⠡⠩⡫⢿⣝⡻⡮⣒⢽⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
  echo -e "—————————————————————————————"
}

generate() {
  item() { echo -e "\n- $@"; }
  die() { 
    echo -e "\n\n! $@"
    exit 1
  }
  file_getprop() { grep "^$2=" "$1" 2>/dev/null | tail -n1 | cut -d= -f2-; }

  main() {
    case $1 in
    json|prop) FORMAT=$1;;
    "") FORMAT=json;;
    esac;
    item "Using format: $FORMAT";

    [ ! -f build.prop ] && [ ! -f system-build.prop -o ! -f product-build.prop ] \
      && die "No build.prop files found in script directory";

    item "Parsing build.prop(s) ...";

    PRODUCT=$(file_getprop build.prop ro.product.name);
    DEVICE=$(file_getprop build.prop ro.product.device);
    MANUFACTURER=$(file_getprop build.prop ro.product.manufacturer);
    BRAND=$(file_getprop build.prop ro.product.brand);
    MODEL=$(file_getprop build.prop ro.product.model);
    FINGERPRINT=$(file_getprop build.prop ro.build.fingerprint);
    FORCE_BASIC_ATTESTATION="false"

    [ -z "$PRODUCT" ] && PRODUCT=$(file_getprop build.prop ro.product.system.name);
    [ -z "$DEVICE" ] && DEVICE=$(file_getprop build.prop ro.product.system.device);
    [ -z "$MANUFACTURER" ] && MANUFACTURER=$(file_getprop build.prop ro.product.system.manufacturer);
    [ -z "$BRAND" ] && BRAND=$(file_getprop build.prop ro.product.system.brand);
    [ -z "$MODEL" ] && MODEL=$(file_getprop build.prop ro.product.system.model);
    [ -z "$FINGERPRINT" ] && FINGERPRINT=$(file_getprop build.prop ro.system.build.fingerprint);

    case $DEVICE in
      generic) die "Generic /system/build.prop values found, rename to system-build.prop and add product-build.prop";;
    esac;

    [ -z "$PRODUCT" ] && PRODUCT=$(file_getprop product-build.prop ro.product.product.name);
    [ -z "$DEVICE" ] && DEVICE=$(file_getprop product-build.prop ro.product.product.device);
    [ -z "$MANUFACTURER" ] && MANUFACTURER=$(file_getprop product-build.prop ro.product.product.manufacturer);
    [ -z "$BRAND" ] && BRAND=$(file_getprop product-build.prop ro.product.product.brand);
    [ -z "$MODEL" ] && MODEL=$(file_getprop product-build.prop ro.product.product.model);
    [ -z "$FINGERPRINT" ] && FINGERPRINT=$(file_getprop product-build.prop ro.product.build.fingerprint);

    if [ -z "$FINGERPRINT" ]; then
      if [ -f build.prop ]; then
        die "No fingerprint found, use a /system/build.prop to start";
      else
        die "No fingerprint found, unable to continue";
      fi;
    fi;
    echo "$FINGERPRINT";

    LIST="PRODUCT DEVICE MANUFACTURER BRAND MODEL FINGERPRINT";

    item "Parsing build UTC date ...";
    UTC=$(file_getprop build.prop ro.build.date.utc);
    [ -z "$UTC" ] && UTC=$(file_getprop system-build.prop ro.build.date.utc);
    date -u -d @$UTC;

    if [ "$UTC" -gt 1521158400 ]; then
      item "Build date newer than March 2018, adding SECURITY_PATCH ...";
      SECURITY_PATCH=$(file_getprop build.prop ro.build.version.security_patch);
      [ -z "$SECURITY_PATCH" ] && SECURITY_PATCH=$(file_getprop system-build.prop ro.build.version.security_patch);
      LIST="$LIST SECURITY_PATCH";
      echo "$SECURITY_PATCH";
    fi;

    item "Parsing build first API level ...";
    FIRST_API_LEVEL=$(file_getprop vendor-build.prop ro.product.first_api_level);
    [ -z "$FIRST_API_LEVEL" ] && FIRST_API_LEVEL=$(file_getprop vendor-build.prop ro.board.first_api_level);
    [ -z "$FIRST_API_LEVEL" ] && FIRST_API_LEVEL=$(file_getprop vendor-build.prop ro.board.api_level);

    if [ -z "$FIRST_API_LEVEL" ]; then
      [ ! -f vendor-build.prop ] && die "No first API level found, add vendor-build.prop";
      item "No first API level found, falling back to build SDK version ...";
      [ -z "$FIRST_API_LEVEL" ] && FIRST_API_LEVEL=$(file_getprop build.prop ro.build.version.sdk);
      [ -z "$FIRST_API_LEVEL" ] && FIRST_API_LEVEL=$(file_getprop build.prop ro.system.build.version.sdk);
      [ -z "$FIRST_API_LEVEL" ] && FIRST_API_LEVEL=$(file_getprop system-build.prop ro.build.version.sdk);
      [ -z "$FIRST_API_LEVEL" ] && FIRST_API_LEVEL=$(file_getprop system-build.prop ro.system.build.version.sdk);
      [ -z "$FIRST_API_LEVEL" ] && FIRST_API_LEVEL=$(file_getprop vendor-build.prop ro.vendor.build.version.sdk);
      [ -z "$FIRST_API_LEVEL" ] && FIRST_API_LEVEL=$(file_getprop product-build.prop ro.product.build.version.sdk);
    fi;
    echo "$FIRST_API_LEVEL";

    if [ "$FIRST_API_LEVEL" -gt 32 ]; then
      item "First API level 33 or higher, resetting to 32 ...";
      FIRST_API_LEVEL=32;
    fi;
    LIST="$LIST FIRST_API_LEVEL";
    if [ "$FIRST_API_LEVEL" -gt 25 ]; then
      item "First API level is Oreo or higher, adding FORCE_BASIC_ATTESTATION property..."
      FORCE_BASIC_ATTESTATION="true"
      LIST="$LIST FORCE_BASIC_ATTESTATION"
    fi;
    

    if [ -f custom.pif.$FORMAT ]; then
      item "Removing existing custom.pif.$FORMAT ...";
      rm -f custom.pif.$FORMAT;
    fi;

    item "Writing new custom.pif.$FORMAT ...";
    [ "$FORMAT" == "json" ] && echo '{' | tee -a custom.pif.json;
    for PROP in $LIST; do
      case $FORMAT in
        json) eval echo '\ \ \"$PROP\": \"'\$$PROP'\",';;
        prop) eval echo $PROP=\$$PROP;;
      esac;
    done | sed '$s/,//' | tee -a custom.pif.$FORMAT;
    [ "$FORMAT" == "json" ] && echo '}' | tee -a custom.pif.json;

    echo
    echo "Done!"
    cd ../
  }

  manual_gen() {
    case $0 in
      *.sh)
          shdir="$0"
          ;;
        *)
          shdir="$(lsof -p $$ 2>/dev/null | grep -o '/.*gen_pif_custom.sh$')"
          ;;
    esac
    shdir=$(dirname "$(readlink -f "$shdir")")

    echo -e "# Choose your cloned directory by referencing the number next to\
      \n# each directory name. (do not select any empty name directories)";
    dir_arr=("no")
    readarray -t temp_arr < <(ls -F | grep "/$" | cut -d'/' -f1)
    dir_arr+=(${temp_arr[@]})
    for ((a = 1 ; a < ${#dir_arr[@]} ; a++)); do
      echo "${a}. ${dir_arr[$a]}"
    done

    echo ""
    read -p "Enter number: " arr_index
    if [[ "$arr_index" =~ ^+[0-9]+$ ]]; then
      if [ "$arr_index" -gt "${#dir_arr[@]}" ] || [ "$arr_index" -lt 0 ]; then
        echo "Invalid index!"
        echo "Exiting..."
        exit 1
      else
        cd $shdir
        cd ${dir_arr[$arr_index]}
        main
      fi
    else
      echo "Not a number!"
    fi
    
  }

  if $manual; then
    manual_gen
  else
    main
  fi
}

clone_repo() {
  local input="$1"
  # single file checkouts for inputed repo
  checkout() {
    echo -e "\n# Try to get build.prop from system dirs"
    git checkout $br -- system/build.prop
    git checkout $br -- system/system/build.prop

    echo -e "\n# Try to get build.prop from system/product dirs"
    git checkout $br -- system/system/product/build.prop
    git checkout $br -- system/product/build.prop

    echo -e "\n# Try to get build.prop from vendor dirs"
    echo
    git checkout $br -- vendor/build.prop 
    git checkout $br -- system/vendor/build.prop

    rename
  }

  # rename and move files that are clones
  rename() {
    echo -e "\n# Rename and move files..."
    if [ -f "system/product/build.prop" ]; then
      mv system/product/build.prop ./product-build.prop
    elif [ -f "system/system/product/build.prop" ]; then
      mv system/system/product/build.prop ./product-build.prop
    fi

    if [ -f "system/build.prop" ]; then
      mv system/build.prop ./
    elif [ -f "system/system/build.prop" ]; then
      mv system/system/build.prop ./
    fi

    if [ -f "system/vendor/build.prop" ]; then
        mv system/vendor/build.prop ./vendor-build.prop
    fi
    if [ -f "vendor/build.prop" ]; then
      mv vendor/build.prop ./vendor-build.prop
    fi

    delete
  }

  # delete empty folders when finished
  delete() {
    if [ -d "system" ]; then
    rm -rf system
    fi
    if [ -d "vendor" ]; then
      rm -rf vendor
    fi

    if $manual; then
      cd ../
    fi
  }
  # main code for cloning
  if $file; then
    url=$input
  elif $short || $manual; then
    read -p "Paste repo URL here: " url
  else
    megamind "No arguments"
    return 1
  fi
  
  if [ "$url" = ""  ]; then
    megamind "No repo link"
    echo -e "# Please Note!!"
    echo -e "# Make sure you are pasting the proper URL" \
    "\n# URL formats such as https://dumps.tadiphone.dev/dumps/asus/asus_i007_1.git"
    echo -e "# Rerun program after copying the correct URL"
    exit 1
  elif [[ $(echo "$url" | grep "https://") != "" ]] && [[ $(echo "$url" | grep ".git") != "" ]]; then
    IFS='/' read -r -a url_arr <<< "$url"
    IFS='.' read -r -a git_dir_arr <<< "${url_arr[-1]}"
    git_dir=${git_dir_arr[0]}

    if [ -d "${git_dir[0]}" ]; then
      echo "Directory already exists. Skipping clone..."
    else
      git clone --depth 1 --no-checkout --filter=blob:none ${url}
    fi

    cd ${git_dir[0]}
    branch_out=$(git branch)
    IFS=' ' read -r -a br_arr <<< "$branch_out"
    br=${br_arr[-1]}

    # Checkout with outputs suppressed to a output file
    checkout &> out.txt
  else
    echo -e "# Invalid URL!"
    echo -e "# Please rerun script and paste a valid git URL."
    return 1
  fi
}

usage() {
  local usage_only="$1"
  if [ "$usage_only" = "yes" ]; then
    echo -e "Usage: $(basename "$0") [-m option] or [-s] or [-f file]"
  else
    echo -e "Usage: $(basename "$0") [-m option] or [-s] or [-f file]"
    echo -e "See 'start -h' for help"
  fi
}

manual="false"
short="false"
file="false"
help="false"
flag=""
flag_count=0

while getopts 'm:sf:h' OPT; do
  case "$OPT" in
    m)
      manual="true"
      flag="$OPT"
      mode=${OPTARG}
      if [ "$3" != "" ]; then
        echo -e "Error: More than one mode supplied."
        usage
        exit 1
      fi
      ;;
    s)
      short="true"
      flag="$OPT"
      ;;
    f)
      file="true"
      flag="$OPT"
      filename=${OPTARG}
      if [ "$3" != "" ]; then
        echo -e "Error: More than one file supplied."
        usage
        exit 1
      fi
      ;;
    h)
      help="true"
      flag="$OPT"
      
      ;;
    *)
      flag="$OPT"
      ;;
  esac
  flag_count=$((flag_count + 1))
done
shift $((OPTIND-1))

if [ "$flag_count" -gt 1 ]; then
  echo -e "Error: Multiple mutually exclusive flags cannot be used simultaneously.\n"
  usage
  exit 1
fi

case $flag in
  m)
    if [ "$mode" = "pif" ]; then
      generate
    elif [ "$mode" = "clone" ]; then
      clone_repo
    else
      echo -e "Error: Unknown mode $mode. Input a valid argument for -m."
      usage
      exit 1
    fi
    ;;
  s)
    echo -e "----- Short mode -----"
    clone_repo
    generate
    ;;
  f)
    echo -e "----- Bulk generation mode -----"
    if [ -f $filename ]; then
      readarray -t repo_list < <(cat $filename)
      for repo in ${repo_list[@]}; do
        clone_repo $repo
        generate
      done
    else
      echo "Error: File not found. Make sure you have inputed the correct filename or path."
    fi
    ;;
  h)
    usage "yes"
    echo -e " -m [clone, pif]     Manual generation. Select running one functionality at a time."
    echo -e "                     Use the 'clone' option to only clone a repo."
    echo -e "                     Use the 'pif' option to only generate a fingerprint json manually.\n"
    echo -e " -s                  Short version. Run the script with less hassle. Just have the repo"
    echo -e "                     link ready in your clipboard.\n"
    echo -e " -f [file-path]      For bulk generation. It requires a text file with a list of device"
    echo -e "                     repo links separated by newlines.\n"
    echo -e " -h                  Prints this screen.\n"
    ;;
  *)
    if [ "$flag" = "" ]; then
    echo -e "Error: Make sure at least one argument is passed and that your argument is not more than one.\n"
    usage
    else
      usage
      exit 1
    fi
    ;;
esac
